version: 2
jobs:
  unittest:
    docker:
      - image: circleci/golang:1.13
      - image: redis
    working_directory: /go/src/github.com/joway/pikv
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-cache-{{ checksum "go.sum" }}
      - run: sudo apt update && sudo apt install -y gcc
      - run: curl -sfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh| sh -s -- -b $(go env GOPATH)/bin v1.21.0
      - run: mkdir -p /tmp/pikv
      - run: make
      - save_cache:
          key: v1-cache-{{ checksum "go.sum" }}
          paths:
            - "vendor"
      - run: make fmt-check
      - run: make test
      - run: E2E_REDIS_ENABLE=true E2E_ENDPOINT=127.0.0.1:6379 make e2e
      - run: bash <(curl -s https://codecov.io/bash)
  install:
    docker:
      - image: circleci/golang:1.13
    steps:
      - run: mkdir -p ~/.ssh/ && echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
      - run: go get github.com/joway/pikv/...@$CIRCLE_BRANCH
      - run: pikv -v
  publish-release:
    docker:
      - image: circleci/buildpack-deps:stretch
    steps: &publishStep
      - checkout
      - setup_remote_docker
      - run: make docker-build
      - run:
          name: Publish Docker Image to Docker Hub
          command: |
            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USER" --password-stdin
            make docker-push
  publish-nightly:
    docker:
      - image: circleci/buildpack-deps:stretch
    environment:
      DOCKER_TAG: nightly
    steps: *publishStep
  publish-latest:
    docker:
      - image: circleci/buildpack-deps:stretch
    environment:
      DOCKER_TAG: latest
    steps: *publishStep
workflows:
  version: 2
  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - publish-nightly:
          context: docker
  pipeline:
    jobs:
      - unittest:
          filters:
            tags:
              only: /.*/
      - install:
          filters:
            tags:
              only: /.*/
      - publish-latest:
          context: docker
          filters:
            tags:
              only: /.*/
            branches:
              only:
                - master
      - publish-release:
          context: docker
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
          requires:
            - unittest
            - install
