version: 2
jobs:
  test:
    docker:
      - image: circleci/golang:1.11
    working_directory: /go/src/github.com/joway/pikv
    steps:
      - checkout
      - run: sudo apt update && sudo apt install -y gcc
      - run: curl -sfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh| sh -s -- -b $(go env GOPATH)/bin v1.21.0
      - run: mkdir -p /tmp/pikv
      - run: env GO111MODULE=on make
      - run: env GO111MODULE=on make fmt-check
      - run: env GO111MODULE=on make test
      - run: bash <(curl -s https://codecov.io/bash)
  install:
    docker:
      - image: circleci/golang:1.11
    steps:
      - run: mkdir -p ~/.ssh/ && echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
      - run: go get github.com/joway/pikv
      - run: pikv -v
  publish:
    docker:
      - image: circleci/buildpack-deps:stretch
    steps:
      - checkout
      - setup_remote_docker
      - run: make docker-build
      - run:
          name: Publish Docker Image to Docker Hub
          command: |
            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USER" --password-stdin
            make docker-push
workflows:
  version: 2
  pipeline:
    jobs:
      - test
      - install
      - publish:
          context: docker
          requires:
            - test
            - install
          filters:
            branches:
              only: master
