version: 2
jobs:
  unittest:
    docker:
      - image: circleci/golang:1.12
      - image: redis
    working_directory: /go/src/github.com/joway/pikv
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-cache-{{ checksum "go.sum" }}
      - run: sudo apt update && sudo apt install -y gcc
      - run: curl -sfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh| sh -s -- -b $(go env GOPATH)/bin v1.21.0
      - run: mkdir -p /tmp/pikv
      - run: make
      - save_cache:
          key: v1-cache-{{ checksum "go.sum" }}
          paths:
            - "vendor"
      - run: make fmt-check
      - run: make test
      - run: E2E_REDIS_ENABLE=true E2E_ENDPOINT=127.0.0.1:6379 make e2e
      - run: bash <(curl -s https://codecov.io/bash)
  install:
    docker:
      - image: circleci/golang:1.11
    steps:
      - run: mkdir -p ~/.ssh/ && echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
      - run: go get github.com/joway/pikv/...
      - run: pikv -v
  publish:
    docker:
      - image: circleci/buildpack-deps:stretch
    steps:
      - checkout
      - setup_remote_docker
      - run: make docker-build
      - run:
          name: Publish Docker Image to Docker Hub
          command: |
            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USER" --password-stdin
            make docker-push
workflows:
  version: 2
  pipeline:
    jobs:
      - unittest:
          filters:
            tags:
              only: /.*/
      - install:
          filters:
            tags:
              only: /.*/
      - publish:
          context: docker
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
          requires:
            - unittest
            - install
