version: 2
jobs:
  unittest:
    docker:
      - image: circleci/golang:1.13
      - image: redis
    working_directory: /go/src/github.com/joway/pikv
    environment:
      GO111MODULE: 'on'
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-cache-{{ checksum "go.sum" }}
      - run: curl -sfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh| sh -s -- -b $(go env GOPATH)/bin v1.21.0
      - run: mkdir -p /tmp/pikv
      - run: make
      - save_cache:
          key: v1-cache-{{ checksum "go.sum" }}
          paths:
            - "vendor"
      - run: make fmt-check
      - run: make test
      - run: E2E_REDIS_ENABLE=true E2E_ENDPOINT=127.0.0.1:6379 make e2e
      - run: bash <(curl -s https://codecov.io/bash)
  benchmark:
    docker:
      - image: circleci/golang:1.13
      - image: redis
      - image: mutschler/ledisdb
        command: "ledis-server --config=/config.toml -addr 0.0.0.0:6381"
      - image: alash3al/redix
        command: "-resp-addr 0.0.0.0:6382"
    environment:
      GO111MODULE: 'on'
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-cache-{{ checksum "go.sum" }}
      - run:
          name: Install pkg
          command: |
            sudo apt update
            sudo apt install -y redis-server \
            build-essential autoconf automake libpcre3-dev \
            libevent-dev pkg-config zlib1g-dev libssl-dev

            git clone https://github.com/RedisLabs/memtier_benchmark.git
            cd memtier_benchmark
            autoreconf -ivf && ./configure && make && sudo make install
      - run: mkdir -p /tmp/pikv
      - run: make
      - run: nohup ./bin/pikv -p 6380
      - save_cache:
          key: v1-cache-{{ checksum "go.sum" }}
          paths:
            - "vendor"
      - run:
          name: Redis Benchmark redis
          command: redis-benchmark -p 6379 -q -t SET,GET -P 1024 -r 1000000000 -n 1000000
      - run:
          name: Redis Benchmark pikv
          command: redis-benchmark -p 6380 -q -t SET,GET -P 1024 -r 1000000000 -n 1000000
      - run:
          name: Redis Benchmark ledisdb
          command: redis-benchmark -p 6381 -q -t SET,GET -P 1024 -r 1000000000 -n 1000000
      - run:
          name: Redis Benchmark redix
          command: redis-benchmark -p 6382 -q -t SET,GET -P 1024 -r 1000000000 -n 1000000
      - run:
          name: Memtier Benchmark redis
          command: memtier_benchmark -s 0.0.0.0 -p 6379 --hide-histogram
      - run:
          name: Memtier Benchmark pikv
          command: memtier_benchmark -s 0.0.0.0 -p 6380 --hide-histogram
      - run:
          name: Memtier Benchmark ledisdb
          command: memtier_benchmark -s 0.0.0.0 -p 6381 --hide-histogram
      - run:
          name: Memtier Benchmark redix
          command: memtier_benchmark -s 0.0.0.0 -p 6382 --hide-histogram
  install:
    docker:
      - image: circleci/golang:1.13
    environment:
      GO111MODULE: 'on'
    steps:
      - run: mkdir -p ~/.ssh/ && echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
      - run: go get github.com/joway/pikv/...@$CIRCLE_BRANCH
      - run: pikv -v
  publish-release:
    docker:
      - image: circleci/buildpack-deps:stretch
    steps: &publishStep
      - checkout
      - setup_remote_docker
      - run: make docker-build
      - run:
          name: Publish Docker Image to Docker Hub
          command: |
            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USER" --password-stdin
            make docker-push
  publish-nightly:
    docker:
      - image: circleci/buildpack-deps:stretch
    environment:
      DOCKER_TAG: nightly
    steps: *publishStep
  publish-latest:
    docker:
      - image: circleci/buildpack-deps:stretch
    environment:
      DOCKER_TAG: latest
    steps: *publishStep
workflows:
  version: 2
  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - publish-nightly:
          context: docker
  pipeline:
    jobs:
      - unittest:
          filters:
            tags:
              only: /.*/
      - benchmark:
          filters:
            tags:
              only: /.*/
      - install:
          filters:
            tags:
              only: /.*/
      - publish-latest:
          context: docker
          filters:
            tags:
              only: /.*/
            branches:
              only:
                - master
      - publish-release:
          context: docker
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
          requires:
            - unittest
            - install
            - benchmark
